version: "3"

services:
  db:
    image: mysql:8
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: flights
      MYSQL_PASSWORD: flights
      MYSQL_DATABASE: flights
      MYSQL_ROOT_PASSWORD: flights
  backend:
    restart: always
    build: .
    container_name: backend
    hostname: flights-backend
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      DB_USER: flights
      DB_PASSWORD: flights
      DB_HOST: db
      DB_PORT: 3306
